services:
  api:
    container_name: openquiz_api
    build: ./application
    ports:
      - "${app_port}:4433"
      - "8000:8000"
    volumes:
      - ./application/app:/app/app
      - ./application/hypercorn_config.py:/app/hypercorn_config.py
      - ./.env:/app/app/.env

    depends_on:
      - mongo

  mongo:
    image: mongo:5.5
    container_name: openquiz_mongo
    ports:
      - "${mongo_port}:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "'db.adminCommand(\"ping\")'"]
      interval: ${mongo_health_interval}
      timeout: ${mongo_health_timeout}
      retries: ${mongo_health_retries}

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: openquiz_mongo_express
    ports:
      - "${me_port}:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${mongo_pass}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${mongo_user}
      - ME_CONFIG_MONGODB_SERVER=${mongo_srv}
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
    driver: local