services:
  api:
    build: ./application
    container_name: openquiz_api
    depends_on:
    - mongo
    ports:
    - ${app_port}:4433
    - 8000:8000
    volumes:
    - ./application/app:/app/app
    - ./application/hypercorn_config.py:/app/hypercorn_config.py
    - ./.env:/app/app/.env

  mongo:
    container_name: openquiz_mongo
    healthcheck:
      interval: ${mongo_health_interval}
      retries: ${mongo_health_retries}
      test:
      - CMD
      - mongo
      - --eval
      - '''db.adminCommand("ping")'''
      timeout: ${mongo_health_timeout}
    image: mongo:5.0
    ports:
    - ${mongo_port}:27017
    volumes:
    - mongo_data:/data/db
  
  mongo-express:
    container_name: openquiz_mongo_express
    depends_on:
      mongo:
        condition: service_healthy
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=${mongo_pass}
    - ME_CONFIG_MONGODB_ADMINPASSWORD=${mongo_user}
    - ME_CONFIG_MONGODB_SERVER=${mongo_srv}
    image: mongo-express:1.0.0-alpha.4
    ports:
    - ${me_port}:8081
  
  curl_quic:
    command:
    - sh
    container_name: openquiz_curl_quic
    depends_on:
    - api
    entrypoint: bash
    environment:
      CURL_HTTP3: 'true'
    image: curlimages/curl:latest
    stdin_open: true
    tty: true
    volumes:
    - ./application/app:/app/app

volumes:
  mongo_data:
    driver: local
